service: onondaga-e911

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - README.md
    - package.json
    - package-lock.json
    - Pipfile
    - Pipfile.lock

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource:
        - { "Fn::GetAtt": ["AllEventsTable", "Arn"] }
        - { "Fn::GetAtt": ["ClosedEventsTable", "Arn"] }

functions:

  scrape_all:
    handler: scraper.scrape
    environment:
      SCRAPE_URL: "http://wowbn.ongov.net/CADInet/app/_rlvid.jsp?_rap=pc_Cad911Toweb.doLink1Action&_rvip=/events.jsp"
      DYNAMODB_TABLE: ${self:resources.Resources.AllEventsTable.Properties.TableName}
    events:
      - schedule: rate(1 minute)

  scrape_closed:
    handler: scraper.scrape
    environment:
      SCRAPE_URL: "http://wowbn.ongov.net/CADInet/app/_rlvid.jsp?_rap=pc_Cad911Toweb.doLink7Action&_rvip=/events.jsp"
      DYNAMODB_TABLE: ${self:resources.Resources.ClosedEventsTable.Properties.TableName}
    events:
      - schedule: rate(1 minute)

resources:
  Resources:

    ScrapeUnderScoreAllLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "7"

    ScrapeUnderScoreClosedLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: "7"

    AllEventsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:service}-all-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
          - AttributeName: timestamp_hash
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: timestamp_hash
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ClosedEventsTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:service}-closed-${opt:stage, self:provider.stage}
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
          - AttributeName: timestamp_hash
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: timestamp_hash
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
